version: '3.8'

services:

  document_db:
    image: mongo:4.4
    container_name: document_db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data/mongo:/data/db
  
  mongo_db_gui:
    image: mongo-express
    depends_on:
      - document_db
    container_name: mongo_db_gui
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_AUTH_DATABASE: db
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: document_db


  relational_db:
    image: postgres:13
    container_name: relational_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  postgres_db_gui:
    image: adminer
    container_name: postgres_db_gui
    ports:
      - "8082:8080"
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: example
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    
  
  rabbitmq_gui:
    image: rabbitmq:3-management
    container_name: rabbitmq_gui
    ports:
      - "15673:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: example
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq